[WiP] Creation of content view configuration
thunder/testsite_builder pull request #33
Opened 2020-01-09 13:45 UTC by mtodor

2020-01-20 16:38 UTC, dbosen requested changes
Not related to this PR, but the README should document, that you have to do `GRANT SUPER on *.* to 'drupaluser'@'localhost'`

2020-01-20 16:38 UTC, dbosen commented on src/ConfigTemplateDefinition.php
> +        'resource' => NestedArray::getValue($this->getSourceConfig(), $path),
NestedArray::getValue() expects the first value to be a reference to an array, but ::getSourceConfig() return an array. assigning the output of ::getSourceConfig() beforehand should fix this.

2020-01-20 16:38 UTC, dbosen commented on template/testsite_builder.config_template.views_node_content.yml
> +      source_field: 'status'
All boolean fields do have 'Published / Unpublished' from the status field as display values now, but we want that to be True / False

2020-01-20 16:38 UTC, dbosen commented on src/ConfigTemplateMerge.php
> +    if ($this->tactic == static::SKIP) {
Looks like these comparisons could all be strict "===" comparisons

2020-01-20 16:38 UTC, dbosen commented on src/Plugin/TestsiteBuilder/ConfigTemplateType/ViewBundlePath.php
> +    for ($i = 1; $i < count($path); $i++) {
Yes, it is a micro-optimization, but count should be called outside the for loop :-)

2020-01-21 09:18 UTC, dbosen commented on src/Plugin/TestsiteBuilder/ConfigTemplateType/ViewConfigCacheTag.php
> +  public function __construct(array $configuration, $plugin_id, $plugin_definition, EntityTypeManagerInterface $entity_type_manager) {
you could scrap the __constructor here and in ViewDependencyConfig.php and change the ::create() to 
'
   public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    $plugin = parent::static($configuration, $plugin_id, $plugin_definition);
    $plugin->entityTypeManager = $container->get('entity_type.manager');
    return $plugin;
  } 
'

2020-01-21 09:21 UTC, dbosen commented on template/testsite_builder.config_template.views_node_content.yml
> +          type: 'view_filter'
Lets ghet rid of these inline config, and replace it with the fallback configuration files, that we talked about

2020-01-21 09:26 UTC, dbosen commented on src/Plugin/TestsiteBuilder/ConfigTemplateType/ViewFilter.php
> +  protected function applyPlugConfiguration(string $entity_type, string $bundle, string $field_name, $config) {
This smells like it should also be made into a plugin, as soon as there are more plugin_ids we might want to handle, this gets messy.

2020-02-03 13:45 UTC, mtodor commented
@dbosen all review comments should be addressed.

2020-02-04 08:34 UTC, dbosen approved these changes
Let's do it. It works, and looks ok. We can do all we need for now. The small bugs, we still encounter do not matter ATM. It's more important to get that running.

2020-02-04 08:41 UTC, merged