Refactor field types
thunder/testsite_builder pull request #6
Opened 2019-05-16 15:14 UTC by chrfritsch

2019-05-20 11:29 UTC, mtodor requested changes
When I try the sampled file from one of the sites, I get the following error:
```
In EntityTypeManager.php line 150:
                                                     
  The "some_custom_entity_type" entity type does not exist.  
```

2019-05-20 11:29 UTC, mtodor commented on src/CreatedFieldManager.php
> +    if (!empty($this->map[serialize($field_storage_config)][$bundle])) {
Can we use some hashing here? Something like `default_config_hash`:
```
$data['_core']['default_config_hash'] = Crypt::hashBase64(serialize($data));
```

And can we use `isset` instead of `!empty`?

2019-05-20 11:29 UTC, mtodor commented on src/CreatedFieldManager.php
> +    $fieldManager = \Drupal::service('entity_field.manager');
Can we inject this service?

2019-05-20 11:29 UTC, mtodor commented on src/CreatedFieldManager.php
> +    return $field_storage_config['type'] . '_' . count($defs);
Can we resolve the next name in a simpler way?
You always call `addFieldStorage`, would it be possible to keep some counter for this service and update it with add?

2019-05-20 11:29 UTC, mtodor commented on src/CreatedFieldManager.php
> +    $this->map[serialize($field_storage_config)][$bundle] = $fieldStorageConfig;
Does this `serialize` provides different key from one used in `getFieldStorage`, since you do `unset` before?

P.S. Now I see why you `unset` the `field_name`. Well, you should do that outside `addFieldStorage`.

2019-05-20 11:29 UTC, mtodor commented on src/Annotation/FieldType.php
> +  public $entity_type_id;
Is there a reason for not using camel case here?
I'm not able to see, where are you using that property?

2019-05-20 11:29 UTC, mtodor commented on src/ConfigCreator.php
> +            $testbuilder_field_type = $this->fieldTypePluginManager->createInstance($field_type, $configuration + ['instances' => $field_instances]);
You have no need for `$configuration + ['instances' => $field_instances]`, you can simply move that to initial set of `$configuration`.

If you want to optimize a bit, then you can move set of `$configuration` outside `foreach` and then just add `field_type` and `instances` in the loop.

2019-05-20 11:29 UTC, mtodor commented on src/ConfigCreator.php
> +  protected $notHandledFieldTypes;
It would be good to set this as empty array initially so that later usage with adding values in it works properly.

But, what is this property used for?

2019-05-20 11:29 UTC, mtodor commented on src/Plugin/testsite_builder/FieldType/EntityReferenceRevisions.php
> +    if ($instance['target_type'] == 'paragraph') {
Any ideas to get rid of this target type specific code?
So that we have some generic way of handling target type specific configuration.

2019-05-20 11:29 UTC, mtodor commented on src/Plugin/testsite_builder/FieldType/FieldTypeBase.php
> +    $form_display = entity_get_form_display($this->configuration['entity_type'], $this->configuration['bundle_type'], 'default');
Can we use something else instead of `entity_get_form_display`?

2019-05-20 15:51 UTC, chrfritsch commented on src/Plugin/testsite_builder/FieldType/FieldTypeBase.php
> +    $form_display = entity_get_form_display($this->configuration['entity_type'], $this->configuration['bundle_type'], 'default');
We have to wait for D8.8 for that...

2019-05-21 11:07 UTC, mtodor commented on src/CreatedFieldManager.php
> +    if (!empty($this->createFields[$this->getHash($field_storage_config)][$bundle])) {
It would be better to execute `$this->getHash($field_storage_config)` once and store result in a variable and then just use variable where you need it.

2019-05-21 11:07 UTC, mtodor commented on src/CreatedFieldManager.php
> +    $this->fieldCounter[$field_storage_config['entity_type']][$field_storage_config['type']]++;
I'm getting notices for such code. Exmaple:
```
$a = null;
$a['a']['b']++;
```

2019-05-21 11:07 UTC, mtodor commented on src/CreatedFieldManager.php
> +   * @var int
It should be `array`.

2019-05-21 11:07 UTC, mtodor commented on src/Plugin/testsite_builder/FieldType/FieldTypeBase.php
> +      unset($field_storage_config['field_name']);
Is `unset` relevant only for `if` branch? Can that go inside?

2019-05-21 11:52 UTC, chrfritsch commented on src/CreatedFieldManager.php
> +    $this->fieldCounter[$field_storage_config['entity_type']][$field_storage_config['type']]++;
Use higher PHP version :D

2019-05-22 09:36 UTC, mtodor requested changes

2019-05-22 09:36 UTC, mtodor commented on src/ConfigCreator.php
> +      if ($definition->getBundleEntityType()) {
Can you please set `$definition->getBundleEntityType()` to variable and use it in all places.

2019-05-22 09:36 UTC, mtodor commented on src/ConfigCreator.php
> +      $testbuilder_entity_type = $this->entityTypePluginManager->createInstance($entity_type, ['entity_type' => $entity_type]);
Is it possible to use `$configuration` in `createInstance($entity_type, ['entity_type' => $entity_type]);` call? Or that could be missleading?

2019-05-22 09:36 UTC, mtodor commented on src/ConfigCreator.php
> +      foreach ($this->reportData[$entity_type]['bundle'] as $id => $bundle_config) {
Please use a more descriptive name for `$id` variable. Is it bundle ID (type) or entity type ID?

2019-05-22 09:36 UTC, mtodor commented on src/ConfigCreator.php
> +        $configuration['bundle_type'] = $bundle_entity->id();
Is `$bundle_entity->id();` - same as `$id` from `foreach`?

2019-05-22 09:36 UTC, mtodor commented on src/Plugin/testsite_builder/FieldType/FieldTypeBase.php
> +      unset($field_storage_config['field_name']);
This is still open. Point is, if `$this->getFieldStorageConfig($instance);` does not return `$field_storage_config` with `'field_name'`, then you can move `unset` inside `if` statement.

2019-05-23 10:49 UTC, mtodor requested changes
I'm not able to create any media entities. I get following error when I try to open `/admin/structure/media/manage/group-0`:
```
Error: Call to a member function getLabel() on null in Drupal\media\MediaSourceBase->buildConfigurationForm() (line 199 of .../docroot/core/modules/media/src/MediaSourceBase.php) #0 
```

2019-05-23 10:49 UTC, mtodor commented on src/Plugin/testsite_builder/EntityType/Media.php
> +  public function setMediaSourceManager(MediaSourceManager $mediaSourceManager): void {
Do we need this function to be `public`?

2019-05-23 11:59 UTC, mtodor approved these changes

2019-05-23 11:59 UTC, merged