Add widget definitions
thunder/testsite_builder pull request #8
Opened 2019-05-23 15:12 UTC by chrfritsch

2019-05-27 11:10 UTC, mtodor requested changes

2019-05-27 11:10 UTC, mtodor commented on src/Plugin/testsite_builder/FieldType/FieldTypeBase.php
> +            $match = FALSE;
You can `break` the loop after a first miss is found.

Another thing that you can use is `continue 2;` - in that case, you do not need `$match`. But it's a bit ugly. 😅

2019-05-27 11:10 UTC, mtodor commented on src/Plugin/testsite_builder/FieldType/FieldTypeBase.php
> +          return $this->getWidget($config['entity_type'], $config['bundle'], $config['view_mode'], $config['field']);
This can return `NULL` what didn't happen before and that's also against your function definition `protected function getFieldWidgetConfig(array $instance) : array {`.

If you return `NULL`, will other parts work or you still should fallback to `return ['type' => $fieldTypeDefinitions[$this->configuration['field_type']]['default_widget']];`?

2019-05-27 11:10 UTC, mtodor commented on src/Plugin/testsite_builder/FieldType/FieldTypeBase.php
> +    $module_path = drupal_get_path('module', 'testsite_builder');
I dislike this part. 😞 

What about using the Drupal configuration?

2019-08-06 12:35 UTC, chrfritsch commented
@mtodor's changes are ok. We can merge this

2019-08-06 13:00 UTC, mtodor approved these changes

2019-08-06 13:02 UTC, merged